[mudkip]
title = "chaos-course"
preset = "rtd"
output_dir = "docs/_build"

[mudkip.override]
html_static_path = ["_static"]
language = "ru"
myst_enable_extensions = ["replacements", "tasklist"]
#More fine control of latex creation
#latex_documents = [["index", "chaos.tex", "Demo of PDF Generation", "Author A. Name", "manual"]]

[mudkip.override.latex_elements]
# using code from https://github.com/mazhartsev/sphinx-ru/blob/master/docs/conf.py#L186-L199
# and https://tex.stackexchange.com/a/424514/175151
preamble = "\\usepackage[utf8]{inputenc}"
babel = "\\usepackage[english,main=russian]{babel}"
cmappkg = "\\usepackage{cmap}"
fontenc = "\\usepackage[T1,T2A]{fontenc}"
utf8extra = "\\DeclareUnicodeCharacter{00A0}{\\nobreakspace}"
